services:
  # Наш уже знайомий бекенд
  todo-backend:
    build: ./backend
    container_name: my-todo-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/todo.db:/app/todo.db
    restart: always

  # Наш новий фронтенд
  todo-frontend:
    build: ./frontend
    container_name: my-todo-frontend
    ports:
      - "80:80" # Тепер твій сайт буде відкриватися просто за адресою http://localhost (без портів)
    restart: always
    # Кажемо, що фронтенд запускається тільки після того, як успішно стартує бекенд
    depends_on:
      - todo-backend
